### ISSUE TITLE
Rust support

### ISSUE THREAD

**Issue by lcmartinsfilho** [postmanlabs/postman-code-generators#192]
**Is your feature request related to a problem? Please describe.**
Rust is growing fast and gaining acceptance. Postman lacks Rust examples.

**Describe the solution you'd like**
New code generators in Rust, using Actix, Warp and/or Rocket crates.

**Additional context**
https://github.com/actix/actix
https://github.com/seanmonstar/warp
https://github.com/SergioBenitez/Rocket/tree/v0.4

**Comment by mwilliammyers** [comment]
At the risk of starting a flame-war...

The HTTP client crates in order of _most downloads_ on https://crates.io are:
1. [`reqwest`]
1. [`curl`]
1. [`awc`]
1. [`isahc`]
1. [`atohttpc`]
1. [`ureq`]
1. [`surf`]

I however, humbly think that [`reqwest`](https://crates.io/crates/reqwest), [`surf`](https://crates.io/crates/surf), and [`curl`](https://crates.io/crates/curl) should be top priority (in that order), because they represent the two main async ecosystems: [`tokio`] and [`async-std`], as well as good 'ol `libcurl`.
 
Bonus: [`hyper`](https://crates.io/crates/hyper), which is an HTTP library (which [`reqwest`] and others are built on), not just an HTTP client.

**Additional (semi related) context:**
- https://crates.io/categories/web-programming::http-client?sort=downloads
- https://www.arewewebyet.org/topics/http-clients/
- https://blog.logrocket.com/the-state-of-rust-http-clients/
- https://medium.com/@shnatsel/smoke-testing-rust-http-clients-b8f2ee5db4e6

[`reqwest`]: https://crates.io/crates/reqwest
[`curl`]: https://crates.io/crates/curl
[`awc`]: https://crates.io/crates/awc
[`isahc`]: https://crates.io/crates/isahc
[`atohttpc`]: https://crates.io/crates/atohttpc
[`ureq`]: https://crates.io/crates/ureq
[`surf`]: https://crates.io/crates/surf
[`async-std`]: https://crates.io/crates/async-std
[`tokio`]: https://crates.io/crates/tokio

**Comment by Jobbster** [comment]
Any update on this? would love to see this working

**Comment by dhwaneetbhatt** [comment]
We've added support for generating Rust code snippets using `reqwest` library in the latest version (v10.13) of Postman. Please feel free to try out this feature. Please feel free to provide feedback and contribute directly via issues/PR.
