### ISSUE TITLE
Postman Application could not add appropriate flag to CURL command generated if NTLM authentication is used

### ISSUE THREAD

**Issue by asdf913** [postmanlabs/postman-code-generators#254]
### Information

The version of Postman Application is **7.25.0**
![image](https://user-images.githubusercontent.com/2301325/82781949-c3285880-9e8d-11ea-9905-277a8c8e216d.png)

### Problem

The below screen shot shows that the NTLM authentication is  used for a particular REST API
![image](https://user-images.githubusercontent.com/2301325/82781657-f9190d00-9e8c-11ea-9c84-395e67097145.png)
There is a code button which could generate various type of source code which invoke that selected REST API.
However, the generated CURL command does not have **--ntlm** or **--user** flag.
> curl --location --request GET 'http://*************/reports/api/v2.0/Reports'
![image](https://user-images.githubusercontent.com/2301325/82781800-5a40e080-9e8d-11ea-9197-147201d84f23.png)

**Comment by karmanya007** [comment]
@asdf913 @webholik Does password also be added in the cURL command?

**Comment by akshaydeo** [comment]
Related to #367

**Comment by VShingala** [comment]
@asdf913 @karmanya007  This issue has been fixed with latest version of Postman App v11.6. Below is it working with NTLM auth.


![Image](https://github.com/user-attachments/assets/75cfef81-2606-44de-a300-7634dd322cd4)


We're closing this issue for now but feel free to re-open it if you face any further problems with the fix.
