### ISSUE TITLE
file formdata with same key name not working

### ISSUE THREAD

**Issue by joshuaeduards** [postmanlabs/postman-code-generators#310]
Form-data files with the same key name in postman request is working but when used the generated code, it's not working.

**Comment by umeshp7** [comment]
@joshuaeduards Could you provide the following info?
- Which language are you using to generate code?
- App version
- OS
- Sample of the request and the code generated.

**Comment by webholik** [comment]
In many languages formdata key-value pairs are represented using hashmap, which cannot have duplicate keys. For these languages it is not possible to have multiple formvalues with same keys.

**Comment by umeshp7** [comment]
@joshuaeduards as mentioned by @webholik 
We do not support same name key in some of the codegens because the key-value are stored in a hashmap. This is a known behavior and has limitations from the library used to generate code for these languages. 

Closing this for now. Feel free to reach out if you face any other issue.
