### ISSUE TITLE
js-fetch and nodejs-axios fail dealing line breaks(`\r\n`) in body 

### ISSUE THREAD

**Issue by RikaSugisawa** [postmanlabs/postman-code-generators#350]
**Describe the bug**
When the post body includes line breaks(`\r\n`), (at least in `multipart/form-data` requests), the code in body part didn't escape `\r`.

**To Reproduce**
Generate code for request whose body contains `\r`

**Expected code snippet and corresponding request**
escape `\r`

**Screenshots**
![图片](https://user-images.githubusercontent.com/22655313/94895777-a09eef80-04be-11eb-92ce-cfa40a0a7763.png)

Version of postman-code-generators/Postman app:
v7.33.1

**Comment by webholik** [comment]
@RikaSugisawa Are you manually setting the header and body? Because for `mutlipart/form-data` requests, both `js-fetch` and `nodejs-axios` use `form-data` library to handle body.

For example:
![Screenshot_20201021_152334](https://user-images.githubusercontent.com/360759/96704444-b878dd80-13b1-11eb-9956-165b0c56f4d8.png)
![Screenshot_20201021_152431](https://user-images.githubusercontent.com/360759/96704454-bc0c6480-13b1-11eb-9be0-f953b50c8653.png)
