### ISSUE TITLE
escaping space charcter in file path

### ISSUE THREAD

**Issue by Alphasaurs** [postmanlabs/postman-code-generators#396]
I recently clone this repo and run npm install and found that one of dependency that is deepinstall.js is not there in [npmjs](https://www.npmjs.com/search?q=deepinstall.js) so dependecies should be updated.

**Comment by webholik** [comment]
deepinstall.js is not a dependency. It's a script localed in the npm/ folder. You need to run `npm run deepinstall dev` to install the dev dependencies for all the codegens.

**Comment by Alphasaurs** [comment]
@webholik I am facing same error while running the given command `npm run deepinstall dev` 
![2](https://user-images.githubusercontent.com/50196057/97840509-22767880-1d0a-11eb-9021-102339fbc6b6.PNG)

**Comment by umeshp7** [comment]
@Alphasaurs Oh! Thanks for reporting this, looks like the issue is due to a space in the folder name. we are directly using the path without escaping space characters and that is causing the error `Cannot find module 'D:\Open'` 

We'll definitely fix this soon, but as a workaround for now you could try renaming your folder `Open source development` to something without space? This will unblock you and help you to continue using the module. Meanwhile, we'll fix the issue and update here.
