### ISSUE TITLE
Wrong URL Encode

### ISSUE THREAD

**Issue by Farhan25** [postmanlabs/postman-code-generators#435]
**Describe the bug**
There seems to be a bug in URL encode for PHP generator (cURL, HTTP_Request2, pecl_http) and many others languages 

**To Reproduce**
fix the URL encode

**Expected code snippet and corresponding request**
`resource_id=sc-domain%253Aexample.com` is wrong encoing
the right one is `resource_id=sc-domain%3Aexample.com` 

**Screenshots**
![image](https://user-images.githubusercontent.com/12432804/103294949-93c96380-49fb-11eb-8c21-02a1b9a3022b.png)

**Additional context**
the two URLs are different so the whole request would give two separate results.

Version of postman-code-generators/Postman app:
I have the latest version for windows v7.36.1

**Comment by ShauryaAg** [comment]
The issue is that it is not replacing '%' sign correctly when it is passed as params in the Request body.

#### To Reproduce:
Pass a parameter with '%' as value to any key

#### The error:
The error is at line 19 of the [postman-code-generators/codegens/php-curl/lib/util/sanitize.js](https://github.com/postmanlabs/postman-code-generators/blob/31dc9f64295ec47b56c2912901eb39e5bdf067db/codegens/php-curl/lib/util/sanitize.js#L19)

The encodeURIComponent() function parses '%' as '%25'
![image](https://user-images.githubusercontent.com/31778302/103440145-38041200-4c69-11eb-9d1a-a2c81a5c91fa.png)

I would like to contribute to this issue.

**Comment by ShauryaAg** [comment]
The issue is that it is not replacing '%' sign correctly when it is passed as params in the Request body.

#### To Reproduce:
Pass a parameter with '%' as value to any key

#### The error:
Error is at line 111 of [postman-code-generators/codegens/php-curl/lib/php-curl.js/](https://github.com/postmanlabs/postman-code-generators/blob/develop/codegens/php-curl/lib/php-curl.js#L111)

The encodeURI() function parses '%' as '%25'
![image](https://user-images.githubusercontent.com/31778302/103441940-989a4b80-4c77-11eb-810e-184388d1d263.png)


I would like to work on this issue. @abhijitkane

**Comment by Farhan25** [comment]
Well I know what's the problem is, there is double encoding in there which cause the % to be encoded in the second time. 
I just mentioned it to be solved in the next update.
Thanks for your work and if It's necessary I can help you guys :)

**Comment by webholik** [comment]
@Farhan25 Can you share the exact url that you are passing to postman? The one without any encoding applied.

**Comment by ShauryaAg** [comment]
@webholik In that case, one cannot just copy any URL (say from chrome's URL bar), and paste it in Postman's URL Field.

I have made a PR #437 that fixes this issue. Can you please review it?
Thanks

**Comment by Farhan25** [comment]
@ShauryaAg of course, here is a similar one:
https://search.google.com/search-console/links?resource_id=sc-domain%3Aexample.com

the problem is encoding the percentage symbol in the second time (% is encoded as %25).

: => %3A
%3A => %253A

**Comment by VShingala** [comment]
@Farhan25 @ShauryaAg This issue has been fixed for some time now. Do give it a try and let us know if you have any further problems with the fix. i.e. Below is code snippet for the mentioned URL which correctly encodes it now.

![image](https://github.com/user-attachments/assets/70c11f5e-25b3-4f4e-8c28-b2e1f9a9114a)

**Comment by Farhan25** [comment]
Thanks @VShingala , It's been a while! 
I appreciate your prompt attention to this issue and I can confirm that the bug is now resolved exactly as shown in the screenshot.

Have a nice day.
