### ISSUE TITLE
Support generating code snippets for React-native Axios.

### ISSUE THREAD

**Issue by EndLess728** [postmanlabs/postman-code-generators#458]
**Is your feature request related to a problem? Please describe.**
I tried to hit the Instagram API URL in Postman. It is working in Postman but not working for me in react-native. Here is the Link to the issue I posted on [StackOverflow](https://stackoverflow.com/questions/66288967/how-to-solve-status-code-429-on-hitting-an-instagram-api-with-axios) 

**Describe the solution you'd like**
I want the code snippet for react-native which can work as it is working in postman.

**Comment by webholik** [comment]
As per the info on Stack Overflow, Instagram seems to be rate limiting your calls. If it works in Postman, then I think it may be a User-Agent issue. When you send a request through axios it sets the User-Agent to `axios/<version>`. Instagram may be blocking it to prevent bots from putting too much load on their servers. Try adding a new header `User-Agent` and set its value to something unique.

But since you are getting a response, the generated code is working as intended and there is nothing for us to fix here.
