### ISSUE TITLE
Boundaries for multipart requests in plain HTTP are incorrect

### ISSUE THREAD

**Issue by thinkgruen** [postmanlabs/postman-code-generators#616]
**Describe the bug**
Currently, the Code Generator for (plain) HTTP is using the same boundary everywhere instead of following [the RFC](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html). When trying to send the generated code through an HTTP client, e.g. in IntelliJ, the IDE will point out that the boundaries are incorrect, and the request will fail.

**To Reproduce**
- create a POST using a form-data body
- add a key "foo" and text value "bar"
- generate the HTTP code

**Expected code snippet and corresponding request**
The generated code is correct according to the definition of the [aforementioned](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html) RFC which means:
* there is a boundary defined alongside `Content-Type: multipart/form-data` (let's say `xyz`)
* the boundary is used to separate different form data with two additional hyphens before (`--xyz`)
* the request ends with a boundary with two leading and trailing hyphens (`--xyz--`)

**Screenshots**
All boundaries are identical but should follow the rules above.
![A screenshot of the generated code](https://user-images.githubusercontent.com/48723662/166502519-d2bb567d-be28-45e7-9f11-dc94141ef21d.png)

**Additional context**
Version of postman-code-generators/Postman app: 9.16.1

**Comment by saksham-postman** [comment]
This issue was fixxed by this [PR](https://github.com/postmanlabs/postman-code-generators/pull/652)

<img width="387" alt="Screenshot 2024-09-06 at 12 54 01 AM" src="https://github.com/user-attachments/assets/68e995ea-b366-4a37-ad22-6c70feb9d40d">

@VShingala , this can be closed.

**Comment by thinkgruen** [comment]
imho I don't see how the merged fix is better than my proposition which also got submitted earlier.

It just adds additional characters that aren't required. comparing the Content-Length to my PR means that the examples went from 586 to 602 chars (587 or 588 in my proposal) and 581 to 597 (583 or 584 in my proposal).

additionally, the merged PR needed 14 changes as compared to my 6 - adding unneeded complexity (e.g. checking when a loop a is terminated at every iteration...) 

@VShingala please consider reopening this as an optimization to the current solution and let me merge #617 as well.

**Comment by VShingala** [comment]
@saksham-postman let's take detailed look here.

**Comment by saksham-postman** [comment]
Followed up with #768 , merged develop into @thinkgruen branch to resolve conflicts. imo the changes looks good to me

**Comment by mallocash05** [comment]
Hi 👋 I looked into this and opened a PR: #818 
Root cause: the HTTP codegen builds the multipart/form-data body with bare LF (\n) line endings. Per RFC 2046 / RFC 7578, the boundary delimiters and field lines must be terminated with CRLF (\r\n), which is why strict clients like IntelliJ's
HTTP client reject the generated request.

Repro (on latest develop) — a single text field foo=bar generates:
------WebKitFormBoundary7MA4YWxkTrZu0gW\nContent-Disposition: form-data; name="foo"\n\nbar\n-----WebKitFormBoundary7MA4YWxkTrZu0gW--\n
i.e. LF throughout the body.

Fix: switch the form-data body construction to CRLF. Content-Length is derived from the generated body, so it recalculates automatically. I kept the request line/headers as-is to keep the change scoped to the reported body issue — happy to
extend it to the full HTTP message if you'd prefer that.

 Updated the affected fixtures and added a regression test; all 45 unit tests pass and lint is clean. Could you take a look / assign this to me? Thanks!
